### PR TITLE
Recognize parenthesis for negative values

### PR DESCRIPTION
**Pull request by thenaterhood**
Updates currency parsing to identify a number surrounded by parenthesis as a negative number, which is frequently used instead of a minus sign in financial data. This does not change the behaviour for evaluating expressions, which will disable parenthesis from acting in this way.

This means that when passed a value of "(12.30)", the code will parse this as "-12.30" UNLESS "(12.30)" is encountered while evaluating a mathematical expression, in which case it will not be handled as a negative value.

### CODE REVIEW

**Comment by hsoft** [comment]
Interesting, thanks for the PR! The scope of this change is limited, because it can't work on manually typed amount (these are parsed with `parse_amount_expression()`), but it can be used on stuff like CSV imports.

Would you mind throwing in a test please? I'd be delighted to help you get around the test system if you need it.

**Comment by thenaterhood** [comment]
Tests added! I noticed (or at least didn't see) any tests for parsing normal negatives denoted with a minus sign so I added a test for a couple cases of that as well.

With my initial commit I made sure that when parsing expressions things surrounded in parenthesis were not identified as negatives, as that gets really hairy since parenthesis are a grouping symbol and I didn't want to potentially break that. In my use-case it's only imported data that I care about, as a couple of my data sources use the parenthesis notation for negatives.

**Comment by hsoft** [comment]
It looks great, thanks! I'll try it tonight and merge it.

One minor stylistic comment: In the tests, I see that you use positional arguments to pass `False` to `with_expression`. For boolean flags like that, I find it much clearer to pass them as named arguments. Whatcha think?

(and now I'm crossing my fingers, hoping that your use of positional arguments wasn't inspired by code I've written myself...)

**Comment by thenaterhood** [comment]
Hehheh I thought I saw a spot in the tests where that was the case, but I can definitely change it out to pass them as named arguments. I agree that it would probably be more readable, I just have a bad habit of getting super lazy with test code.

**Comment by hsoft** [comment]
Squash-merged in c167d09851e5b98b73858fc0b3a6ac31fc033b22 , thanks!

The flake8 check of tox didn't pass so I fixed it in 9206320dedcd5e79ee86d12cb2629f7f85d04c5d . The rule is that `master` must never fail tox runs.

One day, I'll add automated checks on github PRs so that contributors won't have to know about these rules...

**Pull request closed without merging**
