### PR TITLE
fix #442: Amounts of different currencies can't be compared

### LINKED ISSUE #442: ValueError: Amounts of different currencies can't be compared.
By having reconciled entries of different currencies, we end up with a crash like this one:

```
Traceback (most recent call last):
  File "/usr/bin/moneyguru", line 67, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/moneyguru", line 55, in main
    mgapp = MoneyGuru()
  File "/usr/share/moneyguru/qt/app.py", line 58, in __init__
    self.doc.open(self.prefs.recentDocuments[0])
  File "/usr/share/moneyguru/qt/controller/document.py", line 70, in open
    self.model.load_from_xml(docpath)
  File "/usr/share/moneyguru/core/document.py", line 1167, in load_from_xml
    loader.load()
  File "/usr/share/moneyguru/core/loader/base.py", line 363, in load
    self.oven.cook(datetime.date.min, until_date=None)
  File "/usr/share/moneyguru/core/model/oven.py", line 153, in cook
    self._cook_splits(account, splits)
  File "/usr/share/moneyguru/core/model/oven.py", line 80, in _cook_splits
    split2reconciledbal = self._cook_reconciliation_balances(splits, entries.balance_of_reconciled())
  File "/usr/share/moneyguru/core/model/oven.py", line 72, in _cook_reconciliation_balances
    balance += split.amount
ValueError: Amounts of different currencies can't be compared.
```

This error has been locked down through moneyGuru versions and it's now, I think, not possible to have it "naively", but I've received reports of getting this error when opening old moneyGuru documents, and I can indeed reproduce the problem:

1. New document
2. New account with two reconciled entries
3. Save
4. Open the document with a text editor
5. Go change the currency of one of the entries
6. Open the file
7. Crash

### PR DESCRIPTION
**Pull request by ancientHacker**
Analysis: This error comes from loading older (or hand-edited) files that contain reconciled splits whose amount currency doesn't match their account's currency.  The current versions of MoneyGuru do a good job of preventing users from reconciling such off-currency splits, and also prevents changing an account's currency if doing so would produce off-currency reconciliations, so we believe this problem presents only in files created with older versions.

Fix: When loading saved data, we look for off-currency splits and ignore any saved reconciliation state.  While this produces an in-memory image that differs from the saved state, we don't mark the loaded file as dirty, because the dirty state implies that closing without save and then re-opening the original file would produce a different state, and it won't in this case.  The on-disk reconciliation data is considered to be invalid, and (as of this fix) can never be loaded.

Additional:
1. Any splits that do not have an account but are marked reconciled are also caught by this fix.  We have no evidence that there are files with such splits; there certainly shouldn't be!
2. The currency of splits with a 0 amount is irrelevant, and a reconciled 0 split with an explicit currency that doesn't match the account remains reconciled when it is loaded.
3. There is a new test and a new test data file for this fix.

### CODE REVIEW

**Comment by hsoft** [comment]
Looks good to me, thanks! The only change I'd make is to also add a reference to the originating ticket in the test's comment.  Sometimes, it's not obvious to understand the *raison d'être* of a test and a ticket reference helps greatly.

**Comment by ancientHacker** [comment]
I love it!  That's exactly the self-note I gave myself as I did the PR - "I should have put the issue in the test!"  Will fix that and re-submit.

**Comment by hsoft** [comment]
Thanks!

**Comment by hsoft** [comment]
I forgot to also include the PR in `master`. done now.

**Pull request merged**
