### PR TITLE
Bitcoin currency support and exchange rates

### PR DESCRIPTION
**Pull request by neocogent**
Simple modification of Yahoo provider to support Bitcoin currency and rates.
Still uses Yahoo for rates because they actually do quote BTC. Yay.

Adds two symbols because many people prefer to use mBTC instead of BTC. So I've added BMC for mBTC. Tried mBTC and MBC but the first wouldn't work and the second doesn't group them together in list. so BTC, BMC show up together making it easier to choose. Note, exponent arg of 8 and 5 allow amounts to be shown without loss/rounding.

I've tested this with my own amounts and a few dozen transactions. Seems to work as expected and rate was updating today as price rose $7. Yay, again.

People are always asking about what money manager software they can use with bitcoin. If this gets added in then I'm happy to make a reddit post announcing moneyGuru support for this usage.

### CODE REVIEW

**Comment by hsoft** [comment]
Thanks! I'll have a look soon.

**Comment by neocogent** [comment]
I could actually improve on this. I didn't pay much attention at first but since the rate provider has to get CAD rates this causes poor pricing. For most currencies there is very little difference because Forex arbitrage keeps markets close eg. THB->CAD->USD = THB->USD. But for BTC this is not really the case. Delays and costs to move between various exchanges mean that BTC->CAD->USD is often very different from BTC->USD because the CAD exchange happens at a premium for low market depth. 

I could use the BTCUSD rate from Yahoo and then convert USD -> CAD in the module so that later when users need the USD rate (which is typically the deepest market and most quoted rate) it would be accurate. Right now, if you get BTCUSD it's 420 and BTCCAD + CADUSD it works out to 415 roughly. To do this in the module I would need to lookup in the db USDCAD rate.

**Comment by hsoft** [comment]
@neocogent I don't think it will work. rates are always stored relative to CAD in moneyGuru's rates DB. It's probably a design error, but it's there nonethless.

To have direct BTC->USD rates, we'd have to rework the currency rates system as a whole (significant work).

**Comment by neocogent** [comment]
As long as the USDCAD rate from the db is used to convert and store the BTCUSD rate as a BTCCAD rate, then any following lookup would a good rate. However, it isn't a general solution for any other rate. eg. if someone actually does want to premium BTCCAD rate because they are trading in Canada then they would get the wrong rate. 

Ideally there would need to be a plugin option for which intermediary rate to use, if any, because most intl market rates diverge considerably for BTC. Right now the CNYBTC rate is about $30 US higher than the USD rate.

Well, many Bitcoin users tend to be technical types so possibly just having a setting at the top of the source file to choose the "provider rate" they most prefer. Otherwise it just defaults to using the Yahoo CAD rate, which may be fine for many users.

I'd rather see the plugin available to users even if not perfect, rather than discarding it since it's not ideal. And those who really care could go in and tweak that setting.

BTW I'm also Canadian but spend a lot of my time in Thailand, where it trades at a nice premium. I get paid in BTC for contract programming then exchange it in one of 3 ways - via USD and Paypal, via CAD and eInterac or via THB and coins.co,th (which is usually the best rate).

**Comment by neocogent** [comment]
Ah, I just saw issue #384 which boils down to the same thing, and you make a similar suggestion of using a plugin set native rate adjustment. The only real hassle there is that I don't think there is a way to expose a plugin option in the user interface so it would end up being a file edit. Or perhaps it can query the current "document properties" for the native currency and use that as he source rate, then convert to CAD for storage. Only ideal if the native rate doesn't change often, which is probably true in most cases, though I'll often switch native rate sometimes when I have an urge to see my net worth in Thai baht, then switch it back to USD as my norm.

**Comment by neocogent** [comment]
I've created a new branch with a bitcoin currency provider I'm testing that uses USD as an intermediary. It get the today rate for USDCAD from the db and uses that to make a BTCCAD rate for storage. In my testing it correctly shows values on screen and in the currency table with the Bitfinex (last_price) value. I didn't use Yahoo for this as I noticed they get the price from Coinbase, which I prefer not to use. 

Also note fixed a typo that actually prevented Yahoo quotes in original pull request.

**Comment by hsoft** [comment]
@neocogent regarding your comment about possible moneyGuru options: I would rather change the currency rates DB to work in "full duplex" mode (I just made up this name) where it stores `date/currency1/currency2/rate` rather than `date/currency/rate_in_CAD`. It would probably be a much cleaner approach to fix our problem than trying to add options to mitigate the effect of bad design.

**Comment by hsoft** [comment]
As for the PR itself, the code looks fine, but what about integrating BTC to the existing `yahoo_currency_provider` instead of creating a new plugin? You could to `BMC -> BTC` substitution before the fetch URL is created and add your conditional division by 1000 afterwards, and you'd be good to go.

**Comment by hsoft** [comment]
Also: I've just created #455

**Comment by neocogent** [comment]
I'd be happy to add the code into the existing provider. It may work well for many users though for my own needs I'd like something that uses a more current rate. If you like I'll withdraw the current PR and work on a new combined one.

I have also created another bitcoin_usd_currency_provider I'm testing locally that uses Bitfinex as source. It ran into a glitch this morning as it seems to use an old rate for USDCAD but the last_price rate for BTC giving a wrong resulting value. I'm just confused about what rate is used in Net Worth/Income screens and need to dig a bit more to try and make sure rates are sync'd.

**Comment by hsoft** [comment]
@neocogent you mean the separate branch you talked about earlier? Yeah, I looked at it. It looks fine, but since the USDCAD dance is a bit of a hack, I'd prefer to wait until #455 is implemented before including it directly in moneyGuru.

As for creating a new PR for `yahoo_currency_provider`, I'd appreciate that, thanks.

**Comment by neocogent** [comment]
Yes, I agree. It needs more work. It will be cleaner and work better once #455 has some traction.

**Comment by neocogent** [comment]
I'll probably put my own bitfinex provider on hold until you have a new db schema. It's currently doing odd things - well, to me anyway. It keeps using the default USD rate hard coded (1.028) to fill the BMC table with wrong values. So I guess it's pulling the BMC rate before the USD rate is updated and valid. But despite this the on screen values look ok and seem to be based on current BMC rate. It's just the currency table that's wrong. Well, anyway, no worries about this. 

When you update the db schema I think the currency_provider plugin interface will need an update so that it can return not just a value but a corresponding currency code. eg. (USD, 410.5) which currently would always be eg. (CAD, 562.2). Actually the plugin doesn't need to change but the calling code could just handle both cases of either single float value or tuple with code and know how to update the db when a code is present. That way any existing plugins still work as expected.

**Comment by hsoft** [comment]
yahoo finance service doesn't work anymore.

**Pull request closed without merging**
