### PR TITLE
My changes as discussed per email

### PR DESCRIPTION
**Pull request by lenlo**
In summary:

* I have my preferred system date format set to "YYYY-MM-DD" on my Mac, but moneyGuru insisted on presenting all dates using the North American format of "MM/DD/YY". Tracked down the problem to macOS using "Y" instead of "YYYY" for the date format, which moneyGuru didn't know about. Fixed by replacing it with "YYYY" for now.
* Made the date entry order a user preference. By default, it will be normal left-to-right order in whatever the user's preferred format is, but can be overridden to do the previous day->month->year order by enabling the preference.
* Old currency rates would not be retrieved outside of a 30 day window. You can reproduce this by clearing out currencies.db and opening a moneyGuru file with old transactions in it. Note that the currency rate will stay the same for anything older than 30 days ago. Fixed by queueing up requests for the whole time period in 30 day chunks.
* After upgrading to Python 3.6 using brew on macOS 10.12, moneyGuru would no longer start. The error was "ModuleNotFoundError: No module named 'codecs'". Fixed by normalizing the stdlib path before comparing with it. (See checkin notes for details.)
* When turning on debug logging on a Mac, log output would both go to NSLog as well as stderr, potentially duplicating all log entries if you were to ran the app from the command line. Fixed by supplying our NSLog based log handler directly to the python logger.
* Added support for profiling using cProfile. See the change notes for details. I was wondering why there was a significant delay in starting up moneyGuru on my MacBook Pro with 1 year's worth of transactions. It turned out that the majority of the time was spent in _seek_value_in_CAD, presumably because most of my transactions are in USD. Might be worth making the currency rates table be based on the local currency instead of CAD.
* Every time you ran moneyGuru under macOS 10.12 Sierra, you'd get a warning in the log saying that unencrypted HTTP requests weren't allowed. Fixed by enabling them in Info.plist.

Please send me any questions or comments. Thank you.

### CODE REVIEW

**Comment by hsoft** [comment]
Hi @lenlo , thanks for your contribution! Your code generally looks good, but it's not standard practice to integrate that many changes at once in a single pull request. It would be better if you split each change in separate pull requests. For example, you could cherry-pick your  dfc6094 commit in a new branch and create a "Fixed missing system modules in app wrapper after upgrade to Python 3.6" pull request from it.

This would allow us to have focused discussions on each change before merging. Would you want to do that?

**Comment by lenlo** [comment]
Alright, I can do that... Would you like me to create corresponding "issues" as well?

**Comment by hsoft** [comment]
No, if there are no pre-existing corresponding issues, the PR itself becomes the issue of reference.

**Comment by hsoft** [comment]
Good, thanks. I'll review those PR as soon as I can. Do you mind if we close this PR now?

**Comment by lenlo** [comment]
Sure, I'll do it right away.

**Pull request closed without merging**
